export const MOTIVATIONAL_MESSAGES = [
  "Every small action counts toward a greener future",
  "Your choices today shape tomorrow's environment",
  "Be the change you want to see in the world",
  "Reduce, reuse, rethink your impact",
  "Sustainability starts with you",
  "Together we can make a difference",
  "The planet is in your hands",
  "Living green is living smart",
  "Conscious choices create lasting change",
  "Your carbon footprint matters",
  "One person can spark a movement",
  "Small steps lead to giant leaps for Earth",
  "You have the power to protect our planet",
  "Every eco-choice is a vote for the future",
  "Nature thrives when we care",
  "Your daily habits can heal the world",
  "Think globally, act locally",
  "Green living is good living",
  "The Earth does not belong to us, we belong to it",
  "Progress, not perfection",
  "You are part of the solution",
  "Clean energy, bright future",
  "Less waste, more life",
  "Our actions echo through generations",
  "Climate action starts at home",
  "Protect what you love",
  "A sustainable life is a meaningful life",
  "Every journey begins with a single step",
  "Hope grows when we take action",
  "Tomorrow depends on what we do today",
  "Your impact is bigger than you think",
  "Choose wisely, live kindly",
  "The best time to act is now",
  "Be part of something bigger",
  "Greener choices, brighter tomorrows",
  "Planet Earth is our only home",
  "Lead by example, inspire by action",
  "Small changes, big results",
  "You are making a difference",
  "The future is in your hands",
];

export const OFFSET_OPTIONS = [
  {
    title: "Plant Trees",
    description: "Support reforestation projects worldwide",
    impact: "200 kg CO2/year per tree",
  },
  {
    title: "Renewable Energy Credits",
    description: "Invest in wind and solar power projects",
    impact: "Offset 100% of electricity emissions",
  },
  {
    title: "Carbon Offset Programs",
    description: "Fund verified emission reduction projects",
    impact: "Varies by contribution",
  },
];

// 5 metric tons per year per person is the baseline
export const AVERAGE_ANNUAL_TONS_PER_PERSON = 5;
