export const MOTIVATIONAL_MESSAGES = [
  "Every small action counts toward a greener future",
  "Your choices today shape tomorrow's environment",
  "Be the change you want to see in the world",
  "Reduce, reuse, rethink your impact",
  "Sustainability starts with you",
  "Together we can make a difference",
  "The planet is in your hands",
  "Living green is living smart",
  "Conscious choices create lasting change",
  "Your carbon footprint matters",
  "One person can spark a movement",
  "Small steps lead to giant leaps for Earth",
  "You have the power to protect our planet",
  "Every eco-choice is a vote for the future",
  "Nature thrives when we care",
  "Your daily habits can heal the world",
  "Think globally, act locally",
  "Green living is good living",
  "The Earth does not belong to us, we belong to it",
  "Progress, not perfection",
  "You are part of the solution",
  "Clean energy, bright future",
  "Less waste, more life",
  "Our actions echo through generations",
  "Climate action starts at home",
  "Protect what you love",
  "A sustainable life is a meaningful life",
  "Every journey begins with a single step",
  "Hope grows when we take action",
  "Tomorrow depends on what we do today",
  "Your impact is bigger than you think",
  "Choose wisely, live kindly",
  "The best time to act is now",
  "Be part of something bigger",
  "Greener choices, brighter tomorrows",
  "Planet Earth is our only home",
  "Lead by example, inspire by action",
  "Small changes, big results",
  "You are making a difference",
  "The future is in your hands",

  // 🌍 50 new ones
  "Act as if what you do makes a difference — because it does",
  "Planting hope today grows forests tomorrow",
  "Your lifestyle is your legacy",
  "Eco-friendly is future-friendly",
  "Protecting nature protects ourselves",
  "Every bottle recycled is a step toward balance",
  "Your voice can speak for the voiceless Earth",
  "Green choices are contagious — spread them",
  "The Earth rewards mindful living",
  "Waste less, live more",
  "Your footprint can be light and lasting",
  "Choose planet over convenience",
  "Every habit is a seed for tomorrow",
  "The climate needs heroes, not bystanders",
  "Living simply is living richly",
  "Your actions ripple across oceans",
  "Sustainability is love in practice",
  "Eco-consciousness is modern wisdom",
  "The greenest energy is saved energy",
  "Your choices are powerful votes",
  "Harmony with nature is true progress",
  "Protecting Earth is protecting home",
  "Future generations depend on your present",
  "Every eco-step is a legacy step",
  "Your daily routine can heal the planet",
  "Less plastic, more purpose",
  "The Earth listens to your habits",
  "Your green action inspires another",
  "Sustainability is humanity’s greatest invention",
  "Every choice is a climate choice",
  "The planet thrives when you care",
  "Your impact is your story",
  "Eco-living is future-building",
  "Choose Earth, choose life",
  "Your kindness extends to the planet",
  "Green is the color of hope",
  "Your habits shape humanity’s horizon",
  "Protecting nature is protecting joy",
  "Every eco-action is a love letter to Earth",
  "Your footprint can be a feather’s touch",
  "Living green is living free",
  "Your choices echo in forests and seas",
  "Sustainability is the art of tomorrow",
  "Your eco-voice is louder than you think",
  "Every mindful step is a giant leap for Earth",
  "Your green path lights the way",
  "Eco-actions are timeless gifts",
  "The planet smiles at your care",
  "Your choices are seeds of hope",
  "Green living is global giving",

  // 🌟 10 playful eco-twists on famous quotes
  "Ask not what the Earth can do for you — ask what you can do for the Earth",
  "I have a dream… of clean air and green cities",
  "The only thing we have to fear is climate inaction itself",
  "To be green, or not to be — that is the question",
  "In the beginning, nature created balance — let’s keep it that way",
  "Give me recycling, or give me waste reduction",
  "That’s one small step for you, one giant leap for Earth",
  "The arc of history bends toward sustainability",
  "We shall fight plastic on the beaches, and we shall win",
  "The green revolution will not be televised — it will be lived",
];

export const OFFSET_OPTIONS = [
  {
    title: "Plant Trees",
    description: "Support reforestation projects worldwide",
    impact: "200 kg CO2/year per tree",
  },
  {
    title: "Renewable Energy Credits",
    description: "Invest in wind and solar power projects",
    impact: "Offset 100% of electricity emissions",
  },
  {
    title: "Carbon Offset Programs",
    description: "Fund verified emission reduction projects",
    impact: "Varies by contribution",
  },
];

// 4 metric tons per year per person is the baseline
export const AVERAGE_ANNUAL_TONS_PER_PERSON = 4;
